name: Run Tests

on:
  push:
    branches:
      - Demo  # Trigger action on updates to the Demo branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install pykeepass

    - name: Install software
      run: |
        python3 scripts/software_install.py

    - name: List files
      run: ls -R
      
    - name: Run tests
      run: |
        python3 tests/test_software_install.py
