name: Run Tests on Demo Branch

on:
  push:
    branches:
      - Demo

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chocolatey
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://chocolatey.org/install.ps1 | sudo bash
        shell: bash

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko pykeepass

      - name: Run Software Installation Script
        run: |
          python scripts/software_install.py
        #env:
          #KEEPASS_DB_PATH: ${{ secrets.KEEPASS_DB_PATH }}
          #KEEPASS_PASSWORD: ${{ secrets.KEEPASS_PASSWORD }}

      - name: Run Account Creation Script
        run: |
          python scripts/account_creation.py
        #env:
          #KEEPASS_DB_PATH: ${{ secrets.KEEPASS_DB_PATH }}
          #KEEPASS_PASSWORD: ${{ secrets.KEEPASS_PASSWORD }}

      - name: Run Tests
        run: |
          dpkg -l | grep keepass || echo "KeePass not installed"
          dpkg -l | grep 7zip || echo "7-Zip not installed"
          dpkg -l | grep brave || echo "Brave Browser not installed"
