name: Run Tests on Demo Branch

on:
  push:
    branches:
      - demo

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the appropriate Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko pykeepass  # Install any other dependencies needed

      - name: Run Software Installation Script
        run: |
          python scripts/software_install.py
        env:
          KEEPASS_DB_PATH: ${{ secrets.KEEPASS_DB_PATH }}
          KEEPASS_PASSWORD: ${{ secrets.KEEPASS_PASSWORD }}

      - name: Run Account Creation Script
        run: |
          python scripts/account_creation.py
        env:
          KEEPASS_DB_PATH: ${{ secrets.KEEPASS_DB_PATH }}
          KEEPASS_PASSWORD: ${{ secrets.KEEPASS_PASSWORD }}

      - name: Run Tests
        run: |
          # Add commands to test the setup, e.g., checking if the software was installed correctly
          dpkg -l | grep keepass || echo "KeePass not installed"
          dpkg -l | grep 7zip || echo "7-Zip not installed"
          dpkg -l | grep brave || echo "Brave Browser not installed"
